In [1]:
import numpy as np
import pandas as pd

In [36]:
date = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day34-handling-date-and-time/orders.csv")
time = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day34-handling-date-and-time/messages.csv")

In [37]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [38]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [39]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [40]:
date['date'] = pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
date["date_year"] = date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [13]:
date["date_month"] = date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [14]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [15]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [16]:
date['date_dow_name'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

In [19]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1, 0)
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1

In [21]:
date.drop(columns=['product_id', 'city_id', 'orders'], inplace=True)

date.head()

,date,date_year,date_month,date_month_name,date_day,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,Tuesday,0
1,2018-08-15,2018,8,August,15,Wednesday,0
2,2018-10-23,2018,10,October,23,Tuesday,0
3,2019-08-17,2019,8,August,17,Saturday,1
4,2019-01-06,2019,1,January,6,Sunday,1

In [27]:
# Week of the year?
date['date_weekday'] = date['date'].dt.weekday
date.head()

,date,date_year,date_month,date_month_name,date_day,date_dow_name,date_is_weekend,date_weekday
0,2019-12-10,2019,12,December,10,Tuesday,0,1
1,2018-08-15,2018,8,August,15,Wednesday,0,2
2,2018-10-23,2018,10,October,23,Tuesday,0,1
3,2019-08-17,2019,8,August,17,Saturday,1,5
4,2019-01-06,2019,1,January,6,Sunday,1,6

In [41]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [42]:
time['date'] = pd.to_datetime(time['date'])

In [43]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [44]:
time["hour"] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['second'] = time['date'].dt.second

In [45]:
time.head()

,date,msg,hour,minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [47]:
import datetime
today = datetime.datetime.today()
today - time['date']

0     4649 days 08:02:09.770535
1     4513 days 09:12:09.770535
2     4999 days 08:31:09.770535
3     4301 days 08:21:09.770535
4     4698 days 09:41:09.770535
                 ...
995   5288 days 08:02:09.770535
996   4609 days 09:38:09.770535
997   5074 days 09:15:09.770535
998   5190 days 09:18:09.770535
999   4462 days 09:27:09.770535
Name: date, Length: 1000, dtype: timedelta64[ns]

In [48]:
# days
(today - time['date']).dt.days

0      4649
1      4513
2      4999
3      4301
4      4698
       ...
995    5288
996    4609
997    5074
998    5190
999    4462
Name: date, Length: 1000, dtype: int64

In [51]:
# Months

np.round((today - time['date'])/np.timedelta64(1, 'm'),0)

0      6695042.0
1      6499272.0
2      7199071.0
3      6193941.0
4      6765701.0
         ...
995    7615202.0
996    6637538.0
997    7307115.0
998    7474158.0
999    6425847.0
Name: date, Length: 1000, dtype: float64

In [52]:
(today - time['date'])/np.timedelta64(1, 's')

0      4.017025e+08
1      3.899563e+08
2      4.319443e+08
3      3.716365e+08
4      4.059421e+08
           ...
995    4.569121e+08
996    3.982523e+08
997    4.384269e+08
998    4.484495e+08
999    3.855508e+08
Name: date, Length: 1000, dtype: float64

In [53]:
#hour

(today - time['date'])/np.timedelta64(1, 'h')

0      111584.036047
1      108321.202714
2      119984.519381
3      103232.352714
4      112761.686047
           ...
995    126920.036047
996    110625.636047
997    121785.252714
998    124569.302714
999    107097.452714
Name: date, Length: 1000, dtype: float64