In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
df = np.round(pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day40-iterative-imputer/50_Startups.csv")[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)

In [3]:
df.head()

   R&D Spend  Administration  Marketing Spend  Profit
0       17.0            14.0             47.0    19.0
1       16.0            15.0             44.0    19.0
2       15.0            10.0             41.0    19.0
3       14.0            12.0             38.0    18.0
4       14.0             9.0             37.0    17.0

In [5]:
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
14       12.0            16.0             26.0    13.0
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
44        2.0            15.0              3.0     7.0

In [6]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
14       12.0            16.0             26.0
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
44        2.0            15.0              3.0

In [8]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

C:\Users\FDRA\AppData\Local\Temp\ipykernel_7684\766688332.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
C:\Users\FDRA\AppData\Local\Temp\ipykernel_7684\766688332.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
C:\Users\FDRA\AppData\Local\Temp\ipykernel_7684\766688332.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan

In [9]:
df.head()

    R&D Spend  Administration  Marketing Spend
14       12.0            16.0             26.0
21        NaN            15.0             30.0
37        4.0             5.0             20.0
2        15.0             NaN             41.0
44        2.0            15.0              NaN

In [10]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [11]:
df0

    R&D Spend  Administration  Marketing Spend
14      12.00           16.00            26.00
21       8.25           15.00            30.00
37       4.00            5.00            20.00
2       15.00           12.75            41.00
44       2.00           15.00            29.25

In [13]:

# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
14       12.0           16.00            26.00
21        NaN           15.00            30.00
37        4.0            5.00            20.00
2        15.0           12.75            41.00
44        2.0           15.00            29.25

In [14]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
14           16.00            26.00
37            5.00            20.00
2            12.75            41.00
44           15.00            29.25

In [15]:
y = df1.iloc[[0,2,3,4],0]
y

14    12.0
37     4.0
2     15.0
44     2.0
Name: R&D Spend, dtype: float64

In [16]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

C:\Users\FDRA\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([8.82769987])

In [17]:
df1.iloc[1,0] = 23.14
df1

    R&D Spend  Administration  Marketing Spend
14      12.00           16.00            26.00
21      23.14           15.00            30.00
37       4.00            5.00            20.00
2       15.00           12.75            41.00
44       2.00           15.00            29.25

In [19]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
14      12.00            16.0            26.00
21      23.14            15.0            30.00
37       4.00             5.0            20.00
2       15.00             NaN            41.00
44       2.00            15.0            29.25

In [20]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

    R&D Spend  Marketing Spend
14      12.00            26.00
21      23.14            30.00
37       4.00            20.00
44       2.00            29.25

In [21]:
y = df1.iloc[[0,1,2,4],1]
y

14    16.0
21    15.0
37     5.0
44    15.0
Name: Administration, dtype: float64

In [22]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\FDRA\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([27.50865138])

In [23]:
df1.iloc[3,1] = 11.06
df1

    R&D Spend  Administration  Marketing Spend
14      12.00           16.00            26.00
21      23.14           15.00            30.00
37       4.00            5.00            20.00
2       15.00           11.06            41.00
44       2.00           15.00            29.25

In [24]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

    R&D Spend  Administration
14      12.00           16.00
21      23.14           15.00
37       4.00            5.00
2       15.00           11.06

In [25]:
y = df1.iloc[0:4,-1]
y

14    26.0
21    30.0
37    20.0
2     41.0
Name: Marketing Spend, dtype: float64

In [26]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

C:\Users\FDRA\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([18.85533401])

In [27]:
df1.iloc[4,-1] = 31.56
# After 1st Iteration
df1

    R&D Spend  Administration  Marketing Spend
14      12.00           16.00            26.00
21      23.14           15.00            30.00
37       4.00            5.00            20.00
2       15.00           11.06            41.00
44       2.00           15.00            31.56