# Creating DataFrames
* Let’s look at different ways to create a Pandas DataFrame — the core data structure you’ll be using 90% of the time in data science

In [1]:
import pandas as pd

In [3]:
data = [["jamil", 54], ["jack", 45], ["Sheher", 55]]

data

[['jamil', 54], ['jack', 45], ['Sheher', 55]]

In [6]:
df = pd.DataFrame(data, columns= ["Name", "Marks"])
df

     Name  Marks
0   jamil     54
1    jack     45
2  Sheher     55

In [8]:
data1 = {"a" : [4,5,6], "b": [56,34,343]}
df1 =pd.DataFrame(data1)
df1

   a    b
0  4   56
1  5   34
2  6  343

In [9]:
import numpy as np

In [13]:
arr = np.array([[1,2], [3,4]])

df2 = pd.DataFrame(arr, columns=["A", "B"])
df2

   A  B
0  1  2
1  3  4

In [20]:
import pandas as pd

df3 = pd.read_excel('C:\\Users\\FDRA\\Desktop\\DATA.xlsx')
df3

      Name School  Marks
0  Shubham    SPS     34
1   Joshua    UOS     45
2     Jack    WPS     45
3     Alex    UIS     67
4  Jasmine    RTS     45
5   Sheher    ERT     88
6    Rabia    MRT     77
7    Fisan    HMH     90

In [23]:
pd.read_json("C:\\Users\\FDRA\\Desktop\\Forida\\DTD.json")

    name    lang
0  jamil  Python
1   FRDA  Python

In [32]:
df4 =pd.read_csv('https://www.kaggle.com/datasets/uciml/iris/data?select=Iris.csv')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 9, saw 2

In [29]:
df4

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [30]:
df4.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [31]:
df4.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [34]:
df4.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [36]:
df4.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')