# Merging & Joining Data

In [3]:
import pandas as pd

In [4]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

In [5]:

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [6]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [7]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [9]:
pd.merge(employees, departments, on="DeptID") #inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [11]:
pd.merge(employees, departments, how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [12]:
pd.merge(employees, departments, how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [13]:
pd.merge(employees, departments, how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [15]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})

In [16]:
df1

    Name
0  Alice
1    Bob

In [17]:
df2

      Name
0  Charlie
1    David

In [19]:
pd.concat([df1, df2], axis =1)

    Name     Name
0  Alice  Charlie
1    Bob    David

In [23]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "score": [1, 2]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "age": [45, 78]})

In [27]:
pd.concat([df1, df2], axis =1)

    Name  score     Name  age
0  Alice      1  Charlie   45
1    Bob      2    David   78