In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("messy_customer_sales_data.csv")

In [3]:
df.head(10)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
5,CUST1516,William Day,F,NaN,kolkata,2021-05-02,2025-06-09,27663.0,10.0,richard34@example.net,9463089646,NaN
6,CUST3651,Laura Vincent,male,18.0,BANGALORE,2024-06-16,2025-04-25,NaN,3.0,ymiranda@example.net,6917110630,India
7,CUST10438,Timothy Dunlap,F,43.0 years,Hyderabad,2025-03-16,2025-04-25,18355.0,9.0,christopheranderson@example.net,9981404428,india
8,CUST5189,Sabrina Miller,F,40.0 years,CHENNAI,2025-07-07,2024-10-30,NaN,10.0,shepardcolton@example.net,6233441825,India
9,CUST8237,Mr. Thomas Garcia,F,26.0,NaN,2025-05-24,2024-10-15,28206.0,NaN,heidimartinez@example.org,1225343854,InDia

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                10200 non-null  object
 2   Gender              9174 non-null   object
 3   Age                 9249 non-null   object
 4   City                9184 non-null   object
 5   Signup_Date         10200 non-null  object
 6   Last_Purchase_Date  9188 non-null   object
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  object
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 956.4+ KB

In [5]:
df.describe().round()

       Purchase_Amount  Feedback_Score  Phone_Number
count           9179.0          9177.0  1.020000e+04
mean           29090.0             5.0  4.979974e+09
std           208697.0             3.0  2.902593e+09
min             -500.0             1.0  9.208990e+05
25%            12295.0             3.0  2.449157e+09
50%            24330.0             5.0  4.988639e+09
75%            37130.0             8.0  7.510448e+09
max          9999999.0            10.0  9.994402e+09

In [6]:
df["Age"].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10195     True
10196     True
10197     True
10198     True
10199     True
Name: Age, Length: 10200, dtype: bool

In [7]:
df.isnull().sum()/len(df)*100

Customer_ID           10.029412
Name                   0.000000
Gender                10.058824
Age                    9.323529
City                   9.960784
Signup_Date            0.000000
Last_Purchase_Date     9.921569
Purchase_Amount       10.009804
Feedback_Score        10.029412
Email                  0.000000
Phone_Number           0.000000
Country                7.176471
dtype: float64

In [8]:
df["Age"]

0              52.0
1        51.0 years
2              62.0
3              40.0
4              41.0
            ...
10195    35.0 years
10196          53.0
10197          25.0
10198          55.0
10199          34.0
Name: Age, Length: 10200, dtype: object

In [9]:
df.shape

(10200, 12)

In [10]:
df[df.duplicated()].shape

(15, 12)

In [11]:
df[df.duplicated]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [12]:
df["Customer_ID"].value_counts()

Customer_ID
CUST3374     2
CUST7749     2
CUST10800    2
CUST6588     2
CUST9062     2
            ..
CUST10204    1
CUST4647     1
CUST9548     1
CUST9966     1
CUST4812     1
Name: count, Length: 9000, dtype: int64

In [13]:
df[df["Customer_ID"] == "CUST10204"]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
3400,CUST10204,Christine Parker,FEMALE,53.0,chennai,2021-06-09,2024-12-09,39335.0,5.0,matthew42@example.net,6067083725,India

In [14]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(df[col].value_counts())
        print("_"*50)

Gender
f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: count, dtype: int64
__________________________________________________
City
Kolkata       820
Mumbai        812
Chennai       784
Bangalore     773
Hyderabad     770
Delhi         763
CHENNAI       404
KOLKATA       395
MUMBAI        393
hyderabad     384
bangalore     383
DELHI         378
delhi         369
BANGALORE     363
HYDERABAD     360
mumbai        352
chennai       343
kolkata       338
Name: count, dtype: int64
__________________________________________________
Feedback_Score
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: count, dtype: int64
__________________________________________________
Country
India    7132
IND       793
india     772
InDia     771
Name: count, dtype: int64
__________________________________________________

# Handling Missing Values

In [15]:
df.dropna(subset=["Customer_ID"], inplace=True)

In [16]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [17]:

df["Customer_ID"].value_counts()

Customer_ID
CUST3374     2
CUST7749     2
CUST10800    2
CUST6588     2
CUST9062     2
            ..
CUST10204    1
CUST4647     1
CUST9548     1
CUST9966     1
CUST4812     1
Name: count, Length: 9000, dtype: int64

In [18]:
df["Age"].unique()

array(['52.0', '51.0 years', '62.0', '40.0', '41.0', nan, '18.0',
       '43.0 years', '40.0 years', '26.0', '32.0', '22.0', '59.0', '65.0',
       '61.0', '31.0', '54.0 years', '55.0', '69.0', '61.0 years', '24.0',
       '63.0', '19.0', '50.0', '56.0', '36.0', '68.0', '43.0', '38.0',
       '27.0', '57.0 years', '23.0', '25.0', '66.0', '28.0', '30.0',
       '46.0', '48.0', '20.0', '37.0', '67.0', '51.0', '35.0', '58.0',
       '29.0', 'nan years', '39.0', '49.0', '47.0', '42.0', '44.0',
       '64.0', '53.0', '60.0', '59.0 years', '45.0', '21.0', '34.0',
       '54.0', '48.0 years', '46.0 years', '33.0', '57.0', '30.0 years',
       '58.0 years', '35.0 years', '34.0 years', '69.0 years', '250',
       '19.0 years', '27.0 years', '53.0 years', '65.0 years',
       '66.0 years', '44.0 years', '49.0 years', '25.0 years',
       '23.0 years', '62.0 years', '41.0 years', '33.0 years',
       '28.0 years', '22.0 years', '20.0 years', '42.0 years',
       '45.0 years', '3', '63.0 years', '37.0 years', '38.0 years',
       '55.0 years', '18.0 years', '36.0 years', '67.0 years',
       '29.0 years', '39.0 years', '31.0 years', '47.0 years',
       '52.0 years', '-10', '60.0 years', '24.0 years', '26.0 years',
       '21.0 years', '64.0 years', '50.0 years', '68.0 years',
       '32.0 years', '56.0 years'], dtype=object)

In [19]:
import re

def extract_age(age):
    age_num = re.findall('[0-9]+', str(age))
    if len(age_num) > 0:
        return age_num[0]
    else:
        return age

df["Age"] = df["Age"].apply(lambda x: extract_age(x)).copy()
# df["Age"].unique()

In [20]:
df["Age"] = df["Age"].astype(str).str.extract(r'(\d+)')

In [21]:
df["Age"].unique()

array(['52', '51', '62', '40', '41', nan, '18', '43', '26', '32', '22',
       '59', '65', '61', '31', '54', '55', '69', '24', '63', '19', '50',
       '56', '36', '68', '38', '27', '57', '23', '25', '66', '28', '30',
       '46', '48', '20', '37', '67', '35', '58', '29', '39', '49', '47',
       '42', '44', '64', '53', '60', '45', '21', '34', '33', '250', '3',
       '10'], dtype=object)

In [22]:
df_age = df[df["Age"] != 'nan years']["Age"]

In [23]:
age_median = int(df_age.dropna().astype("int64").median())

In [24]:
age_median

43

In [25]:
df.replace('nan years', age_median, inplace=True)

In [26]:
df["Age"].unique()

array(['52', '51', '62', '40', '41', nan, '18', '43', '26', '32', '22',
       '59', '65', '61', '31', '54', '55', '69', '24', '63', '19', '50',
       '56', '36', '68', '38', '27', '57', '23', '25', '66', '28', '30',
       '46', '48', '20', '37', '67', '35', '58', '29', '39', '49', '47',
       '42', '44', '64', '53', '60', '45', '21', '34', '33', '250', '3',
       '10'], dtype=object)

In [27]:
df["Age"].fillna(age_median, inplace = True)

C:\Users\FDRA\AppData\Local\Temp\ipykernel_3164\3149506877.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(age_median, inplace = True)

In [28]:
df["Age"].unique()

array(['52', '51', '62', '40', '41', 43, '18', '43', '26', '32', '22',
       '59', '65', '61', '31', '54', '55', '69', '24', '63', '19', '50',
       '56', '36', '68', '38', '27', '57', '23', '25', '66', '28', '30',
       '46', '48', '20', '37', '67', '35', '58', '29', '39', '49', '47',
       '42', '44', '64', '53', '60', '45', '21', '34', '33', '250', '3',
       '10'], dtype=object)

In [29]:
df["Purchase_Amount"].fillna(df["Purchase_Amount"].median(), inplace=True)

C:\Users\FDRA\AppData\Local\Temp\ipykernel_3164\666124622.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Purchase_Amount"].fillna(df["Purchase_Amount"].median(), inplace=True)

In [30]:
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41,CHENNAI,2024-04-05,2024-12-15,24268.0,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,f,40,NaN,2024-08-21,2024-10-26,35101.0,1.0,mitchellrivera@example.net,6380823112,India
10195,CUST10767,Robert Lewis,female,35,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10197,CUST6315,Joshua Martinez,m,25,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [31]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [32]:
df["Feedback_Score"].fillna(df["Feedback_Score"].mode(), inplace=True)

C:\Users\FDRA\AppData\Local\Temp\ipykernel_3164\1347394163.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Feedback_Score"].fillna(df["Feedback_Score"].mode(), inplace=True)

In [33]:
df["Feedback_Score"].fillna(df["Feedback_Score"].mode()[0], inplace=True)

C:\Users\FDRA\AppData\Local\Temp\ipykernel_3164\2489240543.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Feedback_Score"].fillna(df["Feedback_Score"].mode()[0], inplace=True)

In [34]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score          0
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [35]:
df["Last_Purchase_Date"].unique()

array(['2025-05-17', '2025-07-22', '2024-12-08', '2025-10-02',
       '2024-12-15', '2025-06-09', '2025-04-25', '2024-10-30',
       '2024-10-15', '2025-01-20', '2025-07-09', '2025-06-29',
       '2025-04-24', '2025-09-03', '2025-03-11', '2025-02-24',
       '2025-09-30', '2024-12-24', '2025-07-18', '2025-03-03',
       '2025-03-26', '2025-01-26', '2024-12-09', nan, '2025-01-09',
       '2025-08-27', '2024-12-31', '2024-11-01', '2025-04-10',
       '2025-07-28', '2025-02-16', '2025-06-05', '2024-12-27',
       '2025-02-11', '2025-02-21', '2024-11-06', '2025-06-27',
       '2024-11-24', '2025-01-30', '2025-05-27', '2025-07-02',
       '2025-03-10', '2025-09-13', '2025-01-25', '2024-12-22',
       '2025-09-18', '2024-10-21', '2025-08-01', '2025-03-23',
       '2025-02-27', '2024-11-28', '2025-02-12', '2025-07-21',
       '2025-09-17', '2024-12-03', '2025-03-19', '2024-12-30',
       '2024-10-23', '2025-02-08', '2025-04-22', '2025-07-14',
       '2024-11-25', '2024-11-09', '2025-05-01', '2025-07-07',
       '2025-07-20', '2025-07-06', '2025-03-18', '2024-12-28',
       '2024-10-09', '2025-10-03', '2025-08-26', '2025-09-27',
       '2025-05-25', '2025-07-10', '2024-11-26', '2025-01-27',
       '2025-05-18', '2025-09-23', '2025-08-17', '2025-01-21',
       '2025-08-31', '2025-02-18', '2025-01-12', '2025-04-15',
       '2025-03-29', '2025-05-04', '2025-06-03', '2025-09-06',
       '2025-07-12', '2024-12-10', '2025-03-15', '2025-05-13',
       '2025-09-14', '2025-03-17', '2025-07-27', '2025-03-02',
       '2025-01-04', '2025-10-06', '2025-07-01', '2024-12-25',
       '2025-03-25', '2025-09-09', '2025-07-13', '2024-11-16',
       '2024-11-19', '2025-02-06', '2024-10-17', '2025-05-03',
       '2025-02-22', '2025-05-09', '2025-05-10', '2024-11-11',
       '2025-05-12', '2025-09-01', '2024-11-05', '2025-03-21',
       '2025-05-21', '2025-06-24', '2025-04-16', '2025-09-12',
       '2025-08-09', '2025-03-07', '2025-02-10', '2025-06-18',
       '2025-08-19', '2024-10-16', '2025-04-27', '2024-12-07',
       '2025-01-16', '2025-06-26', '2025-05-14', '2025-04-11',
       '2024-10-08', '2024-10-20', '2025-09-16', '2025-07-17',
       '2025-01-28', '2025-02-15', '2025-07-24', '2025-01-06',
       '2025-03-05', '2025-04-29', '2024-11-21', '2025-02-17',
       '2025-03-08', '2025-10-04', '2025-03-22', '2025-06-02',
       '2025-09-11', '2025-06-10', '2025-04-06', '2024-11-29',
       '2025-04-04', '2025-02-28', '2025-09-02', '2024-10-27',
       '2025-06-14', '2025-08-30', '2025-02-02', '2025-09-05',
       '2025-07-26', '2025-09-29', '2025-03-30', '2025-08-23',
       '2025-08-24', '2025-08-12', '2025-01-29', '2025-06-21',
       '2025-08-29', '2025-06-16', '2025-10-08', '2025-05-23',
       '2024-12-12', '2025-08-20', '2025-04-14', '2024-12-05',
       '2025-07-16', '2025-05-08', '2024-12-21', '2025-06-30',
       '2025-06-15', '2025-01-08', '2024-12-29', '2025-08-15',
       '2025-01-18', '2025-05-11', '2025-05-05', '2025-06-01',
       '2025-06-08', '2025-01-31', '2024-10-18', '2025-07-31',
       '2024-12-14', '2024-11-02', '2025-02-25', '2024-10-14',
       '2025-07-08', '2025-02-09', '2025-03-12', '2025-08-02',
       '2025-07-23', '2025-08-05', '2025-01-22', '2025-03-20',
       '2025-06-07', '2024-11-07', '2025-06-17', '2025-07-19',
       '2025-04-28', '2025-06-19', '2024-12-20', '2025-08-21',
       '2025-05-02', '2024-11-22', '2025-05-22', '2025-07-15',
       '2025-08-22', '2025-08-08', '2025-03-01', '2025-03-06',
       '2025-04-19', '2025-04-02', '2025-06-23', '2025-08-03',
       '2025-01-01', '2024-11-10', '2025-02-14', '2024-10-11',
       '2025-09-21', '2024-12-01', '2025-07-30', '2025-10-07',
       '2024-10-29', '2025-09-25', '2025-09-10', '2025-03-13',
       '2025-06-25', '2024-12-17', '2025-04-12', '2025-05-31',
       '2025-02-20', '2024-11-23', '2025-03-28', '2025-03-09',
       '2025-06-22', '2024-11-14', '2024-10-28', '2025-09-19',
       '2024-11-03', '2024-12-16', '2025-05-06', '2025-06-20',
       '2025-08-18', '2024-12-26', '2024-12-19', '2024-12-11',
       '2025-01-23', '2025-03-16', '2025-01-11', '2025-04-13',
       '2025-02-23', '2024-12-18', '2025-08-11', '2025-01-24',
       '2025-08-25', '2025-05-15', '2025-03-31', '2025-04-18',
       '2025-08-14', '2025-05-29', '2025-07-04', '2024-10-22',
       '2025-03-24', '2025-04-05', '2025-10-05', '2025-03-14',
       '2025-04-09', '2024-10-19', '2025-04-17', '2025-08-13',
       '2025-04-20', '2025-03-27', '2024-11-13', '2025-09-04',
       '2025-08-07', '2024-10-13', '2025-06-12', '2025-01-02',
       '2024-11-08', '2024-11-27', '2025-04-01', '2025-06-04',
       '2025-09-26', '2025-03-04', '2025-09-20', '2025-02-26',
       '2025-04-07', '2025-09-24', '2025-01-13', '2025-10-01',
       '2025-01-19', '2024-11-12', '2024-10-25', '2024-12-06',
       '2025-04-08', '2025-01-10', '2025-05-28', '2024-12-13',
       '2025-08-16', '2025-01-07', '2024-11-04', '2024-12-02',
       '2025-05-19', '2025-01-14', '2025-02-05', '2025-08-04',
       '2025-08-10', '2024-11-20', '2025-05-26', '2025-05-30',
       '2025-02-01', '2024-11-15', '2025-09-22', '2025-09-15',
       '2025-08-06', '2025-05-24', '2025-02-07', '2024-10-24',
       '2025-02-19', '2025-07-03', '2025-07-25', '2025-06-11',
       '2025-06-28', '2025-02-03', '2025-09-28', '2025-09-08',
       '2025-02-04', '2025-07-05', '2025-07-11', '2025-01-15',
       '2025-04-23', '2025-08-28', '2025-04-03', '2025-05-16',
       '2025-07-29', '2025-06-06', '2024-12-23', '2025-04-21',
       '2025-01-17', '2024-11-17', '2024-10-31', '2024-12-04',
       '2024-10-10', '2025-04-26', '2025-09-07', '2025-01-03',
       '2024-10-12', '2025-05-20', '2025-05-07', '2024-10-26',
       '2025-06-13', '2024-11-30', '2025-04-30', '2024-11-18',
       '2025-02-13', '2025-01-05'], dtype=object)

In [36]:
for col in df[["Gender","City","Country"]]:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\FDRA\AppData\Local\Temp\ipykernel_3164\2052313947.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [37]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                  0
Age                     0
City                    0
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score          0
Email                   0
Phone_Number            0
Country                 0
dtype: int64

In [38]:
df["Last_Purchase_Date"].ffill(inplace=True)

C:\Users\FDRA\AppData\Local\Temp\ipykernel_3164\1840665522.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Last_Purchase_Date"].ffill(inplace=True)

In [39]:
df["Gender"].unique()

array(['m ', 'M', 'F', 'FEMALE', 'f ', 'male', 'MALE', 'female'],
      dtype=object)

In [40]:
df["Gender"].str.lower().unique()

array(['m ', 'm', 'f', 'female', 'f ', 'male'], dtype=object)

In [41]:
df["Gender"] = df["Gender"].str.lower().str.strip()

In [42]:
df["Gender"].replace({"m": "male", "f": "female"}, inplace=True)

C:\Users\FDRA\AppData\Local\Temp\ipykernel_3164\1238306652.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].replace({"m": "male", "f": "female"}, inplace=True)

In [43]:
df["City"]

0           KOLKATA
1           Kolkata
2         hyderabad
3         hyderabad
4           CHENNAI
            ...
10194       Kolkata
10195         delhi
10197     hyderabad
10198       Kolkata
10199     HYDERABAD
Name: City, Length: 9177, dtype: object

In [44]:
df["City"] = df["City"].str.strip().str.lower()

In [45]:
df["Country"].unique()

array(['India', 'india', 'InDia', 'IND'], dtype=object)

In [57]:
df["Country"] = df["Country"].str.lower()

In [58]:
df["Country"] = df["Country"].replace({"ind": "india"})

In [59]:
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,male,52,kolkata,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,india
1,CUST5957,Jason Thomas,male,51,kolkata,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,female,62,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,india
3,CUST2934,Brenda Pierce,female,40,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,female,41,chennai,2024-04-05,2024-12-15,24268.0,8.0,denise84@example.org,2665569480,india
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,female,40,kolkata,2024-08-21,2024-10-26,35101.0,1.0,mitchellrivera@example.net,6380823112,india
10195,CUST10767,Robert Lewis,female,35,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,india
10197,CUST6315,Joshua Martinez,male,25,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,india
10198,CUST4812,Sarah Miller,female,55,kolkata,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,india
10199,CUST6588,David Potter,female,34,hyderabad,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,india

In [66]:
df["Country"].unique()

array(['india'], dtype=object)